swagger: "2.0"
info:
  description: REST API for Apache Spark Spreadsheets
  version: "1.0.0"
  title: Apache Spark Spreadsheets
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
#  /oauth2/dialog:
#    get:
#      operationId: "user.auth.oauth_dialog"
#      tags:
#        - "authorization"
#      responses:
#        200:
#          description: "Successfully got permission"
#      parameters:
#        - name: response_type
#          in: query
#          type: string
#          required: true
#        - name: redirect_uri
#          in: query
#          type: string
#          required: true
#        - name: realm
#          in: query
#          type: string
#          required: true
#        - name: client_id
#          in: query
#          type: string
#          required: true
#        - name: scope
#          in: query
#          type: string
#          required: true
#        - name: state
#          in: query
#          type: string
#          required: true
  /user/login:
    post:
      operationId: "user.auth.login"
      tags:
        - "user"
        - "authorization"
      summary: "Get token for authorization"
      responses:
        200:
          description: "Successfully got token"
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
  /user/register:
    post:
      operationId: "user.auth.register"
      tags:
        - "user"
        - "authorization"
      summary: "Register user"
      responses:
        200:
          description: "Successfully registered user"
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - password
              - passwordVerify
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password:
                type: string
              passwordVerify:
                type: string
  /user/logout:
    get:
      operationId: "user.auth.logout"
      tags:
        - "user"
        - "authorization"
      summary: "User logout"
      responses:
        200:
          description: "User successfully logged out"
  /user/profile:
    get:
      operationId: "user.view"
      tags:
        - "user"
      summary: "Get personal user information"
      responses:
        200:
          description: "Gets logged in user information"
  /session:
    get:
      operationId: "livysession.read"
      tags:
        - "Session"
      summary: "Get list of active sessions"
      description: "Read list of sessions"
      responses:
        200:
          description: "Successfully got list of active sessions"
#      security:
#        - oauth2: [ 'uid' ]
  '/session/{id}':
    delete:
      operationId: "livysession.end"
      tags:
        - "session"
      summary: "End active livy session"
      responses:
        200:
          description: "Successfully ended livy session"
      parameters:
        - name: "id"
          in: "path"
          type: integer
          required: true
  /spreadsheet/files:
    get:
      operationId: "spreadsheets.files.list_files"
      tags:
        - "files"
      summary: "List databases residing in spark"
      description: "List databases"
      responses:
        200:
          description: "Successfully got list of databases"
    post:
      operationId: "spreadsheets.files.create"
      tags:
        - "files"
      summary: "Create database residing in spark"
      description: "Create databases"
      responses:
        200:
          description: "Successfully created database"
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
  /spreadsheet/file/sheets:
    get:
      operationId: "spreadsheets.workbook.get_sheets"
      tags:
        - "file"
        - "spreadsheets"
      summary: "Get list of sheets in the file"
      description: "Get list of sheets in the file"
      responses:
        200:
          description: "Successfully returns sheet listing"
      parameters:
        - name: file
          in: query
          type: string
          required: true
  /spreadsheet/sheet:
    get:
      operationId: "spreadsheets.sheet.view"
      tags:
        - "sheet"
      summary: "Get sheet content in the file"
      description: "Get sheet structure and content"
      responses:
        200:
          description: "Successfully got sheet structure and content"
      parameters:
        - name: file
          in: query
          type: string
          required: true
        - name: sheet
          in: query
          type: string
          required: true
    put:
      operationId: "spreadsheets.workbook.create_sheet"
      tags:
        - "sheet"
      summary: "Add new sheet to the file"
      description: "Add new sheet to the file"
      responses:
        200:
          description: "New sheet created"
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - file
              - sheet
            properties:
              file:
                type: string
              sheet:
                type: string
    post:
      operationId: "spreadsheets.sheet.update"
      tags:
        - "sheet"
      summary: "Update sheet structure"
      description: "Update sheet structure"
      responses:
        200:
          description: "Sheet successfully updated"
  /spreadsheet/sheet/data:
    get:
      operationId: "spreadsheets.sheet.get_data"
      tags:
        - "data"
        - "sheet"
      summary: "Get sheet data"
      description: "Get sheet data"
      responses:
        200:
          description: "Successfully returned data in the sheet"
    post:
      operationId: "spreadsheets.sheet.update_data"
      tags:
        - "sheet"
        - "data"
      summary: "Update sheet data"
      description: "Update sheet data"
      responses:
        200:
          description: "Successfully updated data in the sheet"
      parameters:
        - name: data
          in: body
          schema:
            type: object
            required:
              - file
              - sheet
            properties:
              file:
                type: string
              sheet:
                type: string
              values:
                type: array

#securityDefinitions:
#  oauth2:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: http://localhost:5000/api/oauth2/dialog
#    x-tokenInfoFunc: user.auth.token_info
#    scopes:
#      uid: Unique identifier of the user accessing the service.