swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /session:
    get:
      operationId: "session.read"
      tags:
        - "Session"
      summary: "Get list of active sessions"
      description: "Read list of sessions"
      responses:
        200:
          description: "Successfully got list of active sessions"
  /spreadsheet/files:
    get:
      operationId: "spreadsheets.files.listing"
      tags:
        - "files"
      summary: "List databases residing in spark"
      description: "List databases"
      responses:
        200:
          description: "Successfully got list of databases"
  /spreadsheet/file:
    get:
      operationId: "spreadsheets.file.view"
      tags:
        - "files"
      summary: "Get list of sheets in the file"
      description: "Get list of sheets in the file"
      responses:
        200:
          description: "Successfully returns sheet listing"
  /spreadsheet/sheet:
    get:
      operationId: "spreadsheets.file.sheet.view"
      tags:
        - "sheet"
      summary: "Get sheet content in the file"
      description: "Get sheet structure and content"
      responses:
        200:
          description: "Successfully got sheet structure and content"
    put:
      operationId: "spreadsheets.file.sheet.add"
      tags:
        - "sheet"
      summary: "Add new sheet to the file"
      description: "Add new sheet to the file"
      responses:
        200:
          description: "New sheet created"
    post:
      operationId: "spreadsheets.file.sheet.update"
      tags:
        - "sheet"
      summary: "Update sheet structure"
      description: "Update sheet structure"
      responses:
        200:
          description: "Sheet successfully updated"
  /spreadsheet/sheet/data:
    get:
      operationId: "spreadsheets.file.sheet.data.view"
      tags:
        - "data"
        - "sheet"
      summary: "Get sheet data"
      description: "Get sheet data"
      responses:
        200:
          description: "Successfully returned data in the sheet"
    post:
      operationId: "spreadsheets.file.sheet.data.update"
      tags:
        - "sheet"
        - "data"
      summary: "Update sheet data"
      description: "Update sheet data"
      responses:
        200:
          description: "Successfully updated data in the sheet"

